// Todos los países y territorios con código de marcación propio (ISO 3166-1 alfa-2).
// El nombre es el que se guarda como `country_of_residence`: se conservan los de la lista
// anterior ("Estados Unidos", "República Dominicana"...) para no partir los datos existentes.
export type Pais = { iso: string; nombre: string; dial: string }

export const PAISES: Pais[] = [
  { iso: 'AF', nombre: 'Afganistán', dial: '+93' },
  { iso: 'AL', nombre: 'Albania', dial: '+355' },
  { iso: 'DE', nombre: 'Alemania', dial: '+49' },
  { iso: 'AD', nombre: 'Andorra', dial: '+376' },
  { iso: 'AO', nombre: 'Angola', dial: '+244' },
  { iso: 'AI', nombre: 'Anguila', dial: '+1' },
  { iso: 'AG', nombre: 'Antigua y Barbuda', dial: '+1' },
  { iso: 'SA', nombre: 'Arabia Saudita', dial: '+966' },
  { iso: 'DZ', nombre: 'Argelia', dial: '+213' },
  { iso: 'AR', nombre: 'Argentina', dial: '+54' },
  { iso: 'AM', nombre: 'Armenia', dial: '+374' },
  { iso: 'AW', nombre: 'Aruba', dial: '+297' },
  { iso: 'AU', nombre: 'Australia', dial: '+61' },
  { iso: 'AT', nombre: 'Austria', dial: '+43' },
  { iso: 'AZ', nombre: 'Azerbaiyán', dial: '+994' },
  { iso: 'BS', nombre: 'Bahamas', dial: '+1' },
  { iso: 'BD', nombre: 'Bangladés', dial: '+880' },
  { iso: 'BB', nombre: 'Barbados', dial: '+1' },
  { iso: 'BH', nombre: 'Baréin', dial: '+973' },
  { iso: 'BE', nombre: 'Bélgica', dial: '+32' },
  { iso: 'BZ', nombre: 'Belice', dial: '+501' },
  { iso: 'BJ', nombre: 'Benín', dial: '+229' },
  { iso: 'BM', nombre: 'Bermudas', dial: '+1' },
  { iso: 'BY', nombre: 'Bielorrusia', dial: '+375' },
  { iso: 'BO', nombre: 'Bolivia', dial: '+591' },
  { iso: 'BA', nombre: 'Bosnia y Herzegovina', dial: '+387' },
  { iso: 'BW', nombre: 'Botsuana', dial: '+267' },
  { iso: 'BR', nombre: 'Brasil', dial: '+55' },
  { iso: 'BN', nombre: 'Brunéi', dial: '+673' },
  { iso: 'BG', nombre: 'Bulgaria', dial: '+359' },
  { iso: 'BF', nombre: 'Burkina Faso', dial: '+226' },
  { iso: 'BI', nombre: 'Burundi', dial: '+257' },
  { iso: 'BT', nombre: 'Bután', dial: '+975' },
  { iso: 'CV', nombre: 'Cabo Verde', dial: '+238' },
  { iso: 'KH', nombre: 'Camboya', dial: '+855' },
  { iso: 'CM', nombre: 'Camerún', dial: '+237' },
  { iso: 'CA', nombre: 'Canadá', dial: '+1' },
  { iso: 'BQ', nombre: 'Caribe neerlandés', dial: '+599' },
  { iso: 'QA', nombre: 'Catar', dial: '+974' },
  { iso: 'TD', nombre: 'Chad', dial: '+235' },
  { iso: 'CZ', nombre: 'Chequia', dial: '+420' },
  { iso: 'CL', nombre: 'Chile', dial: '+56' },
  { iso: 'CN', nombre: 'China', dial: '+86' },
  { iso: 'CY', nombre: 'Chipre', dial: '+357' },
  { iso: 'VA', nombre: 'Ciudad del Vaticano', dial: '+39' },
  { iso: 'CO', nombre: 'Colombia', dial: '+57' },
  { iso: 'KM', nombre: 'Comoras', dial: '+269' },
  { iso: 'CG', nombre: 'Congo', dial: '+242' },
  { iso: 'KP', nombre: 'Corea del Norte', dial: '+850' },
  { iso: 'KR', nombre: 'Corea del Sur', dial: '+82' },
  { iso: 'CI', nombre: 'Costa de Marfil', dial: '+225' },
  { iso: 'CR', nombre: 'Costa Rica', dial: '+506' },
  { iso: 'HR', nombre: 'Croacia', dial: '+385' },
  { iso: 'CU', nombre: 'Cuba', dial: '+53' },
  { iso: 'CW', nombre: 'Curazao', dial: '+599' },
  { iso: 'DK', nombre: 'Dinamarca', dial: '+45' },
  { iso: 'DM', nombre: 'Dominica', dial: '+1' },
  { iso: 'EC', nombre: 'Ecuador', dial: '+593' },
  { iso: 'EG', nombre: 'Egipto', dial: '+20' },
  { iso: 'SV', nombre: 'El Salvador', dial: '+503' },
  { iso: 'AE', nombre: 'Emiratos Árabes Unidos', dial: '+971' },
  { iso: 'ER', nombre: 'Eritrea', dial: '+291' },
  { iso: 'SK', nombre: 'Eslovaquia', dial: '+421' },
  { iso: 'SI', nombre: 'Eslovenia', dial: '+386' },
  { iso: 'ES', nombre: 'España', dial: '+34' },
  { iso: 'US', nombre: 'Estados Unidos', dial: '+1' },
  { iso: 'EE', nombre: 'Estonia', dial: '+372' },
  { iso: 'SZ', nombre: 'Esuatini', dial: '+268' },
  { iso: 'ET', nombre: 'Etiopía', dial: '+251' },
  { iso: 'PH', nombre: 'Filipinas', dial: '+63' },
  { iso: 'FI', nombre: 'Finlandia', dial: '+358' },
  { iso: 'FJ', nombre: 'Fiyi', dial: '+679' },
  { iso: 'FR', nombre: 'Francia', dial: '+33' },
  { iso: 'GA', nombre: 'Gabón', dial: '+241' },
  { iso: 'GM', nombre: 'Gambia', dial: '+220' },
  { iso: 'GE', nombre: 'Georgia', dial: '+995' },
  { iso: 'GH', nombre: 'Ghana', dial: '+233' },
  { iso: 'GI', nombre: 'Gibraltar', dial: '+350' },
  { iso: 'GD', nombre: 'Granada', dial: '+1' },
  { iso: 'GR', nombre: 'Grecia', dial: '+30' },
  { iso: 'GL', nombre: 'Groenlandia', dial: '+299' },
  { iso: 'GP', nombre: 'Guadalupe', dial: '+590' },
  { iso: 'GU', nombre: 'Guam', dial: '+1' },
  { iso: 'GT', nombre: 'Guatemala', dial: '+502' },
  { iso: 'GF', nombre: 'Guayana Francesa', dial: '+594' },
  { iso: 'GG', nombre: 'Guernesey', dial: '+44' },
  { iso: 'GN', nombre: 'Guinea', dial: '+224' },
  { iso: 'GQ', nombre: 'Guinea Ecuatorial', dial: '+240' },
  { iso: 'GW', nombre: 'Guinea-Bisáu', dial: '+245' },
  { iso: 'GY', nombre: 'Guyana', dial: '+592' },
  { iso: 'HT', nombre: 'Haití', dial: '+509' },
  { iso: 'HN', nombre: 'Honduras', dial: '+504' },
  { iso: 'HK', nombre: 'Hong Kong', dial: '+852' },
  { iso: 'HU', nombre: 'Hungría', dial: '+36' },
  { iso: 'IN', nombre: 'India', dial: '+91' },
  { iso: 'ID', nombre: 'Indonesia', dial: '+62' },
  { iso: 'IQ', nombre: 'Irak', dial: '+964' },
  { iso: 'IR', nombre: 'Irán', dial: '+98' },
  { iso: 'IE', nombre: 'Irlanda', dial: '+353' },
  { iso: 'IM', nombre: 'Isla de Man', dial: '+44' },
  { iso: 'CX', nombre: 'Isla de Navidad', dial: '+61' },
  { iso: 'NF', nombre: 'Isla Norfolk', dial: '+672' },
  { iso: 'IS', nombre: 'Islandia', dial: '+354' },
  { iso: 'AX', nombre: 'Islas Åland', dial: '+358' },
  { iso: 'KY', nombre: 'Islas Caimán', dial: '+1' },
  { iso: 'CC', nombre: 'Islas Cocos', dial: '+61' },
  { iso: 'CK', nombre: 'Islas Cook', dial: '+682' },
  { iso: 'FO', nombre: 'Islas Feroe', dial: '+298' },
  { iso: 'FK', nombre: 'Islas Malvinas', dial: '+500' },
  { iso: 'MP', nombre: 'Islas Marianas del Norte', dial: '+1' },
  { iso: 'MH', nombre: 'Islas Marshall', dial: '+692' },
  { iso: 'SB', nombre: 'Islas Salomón', dial: '+677' },
  { iso: 'TC', nombre: 'Islas Turcas y Caicos', dial: '+1' },
  { iso: 'VG', nombre: 'Islas Vírgenes Británicas', dial: '+1' },
  { iso: 'VI', nombre: 'Islas Vírgenes de EE. UU.', dial: '+1' },
  { iso: 'IL', nombre: 'Israel', dial: '+972' },
  { iso: 'IT', nombre: 'Italia', dial: '+39' },
  { iso: 'JM', nombre: 'Jamaica', dial: '+1' },
  { iso: 'JP', nombre: 'Japón', dial: '+81' },
  { iso: 'JE', nombre: 'Jersey', dial: '+44' },
  { iso: 'JO', nombre: 'Jordania', dial: '+962' },
  { iso: 'KZ', nombre: 'Kazajistán', dial: '+7' },
  { iso: 'KE', nombre: 'Kenia', dial: '+254' },
  { iso: 'KG', nombre: 'Kirguistán', dial: '+996' },
  { iso: 'KI', nombre: 'Kiribati', dial: '+686' },
  { iso: 'XK', nombre: 'Kosovo', dial: '+383' },
  { iso: 'KW', nombre: 'Kuwait', dial: '+965' },
  { iso: 'LA', nombre: 'Laos', dial: '+856' },
  { iso: 'LS', nombre: 'Lesoto', dial: '+266' },
  { iso: 'LV', nombre: 'Letonia', dial: '+371' },
  { iso: 'LB', nombre: 'Líbano', dial: '+961' },
  { iso: 'LR', nombre: 'Liberia', dial: '+231' },
  { iso: 'LY', nombre: 'Libia', dial: '+218' },
  { iso: 'LI', nombre: 'Liechtenstein', dial: '+423' },
  { iso: 'LT', nombre: 'Lituania', dial: '+370' },
  { iso: 'LU', nombre: 'Luxemburgo', dial: '+352' },
  { iso: 'MO', nombre: 'Macao', dial: '+853' },
  { iso: 'MK', nombre: 'Macedonia del Norte', dial: '+389' },
  { iso: 'MG', nombre: 'Madagascar', dial: '+261' },
  { iso: 'MY', nombre: 'Malasia', dial: '+60' },
  { iso: 'MW', nombre: 'Malaui', dial: '+265' },
  { iso: 'MV', nombre: 'Maldivas', dial: '+960' },
  { iso: 'ML', nombre: 'Mali', dial: '+223' },
  { iso: 'MT', nombre: 'Malta', dial: '+356' },
  { iso: 'MA', nombre: 'Marruecos', dial: '+212' },
  { iso: 'MQ', nombre: 'Martinica', dial: '+596' },
  { iso: 'MU', nombre: 'Mauricio', dial: '+230' },
  { iso: 'MR', nombre: 'Mauritania', dial: '+222' },
  { iso: 'YT', nombre: 'Mayotte', dial: '+262' },
  { iso: 'MX', nombre: 'México', dial: '+52' },
  { iso: 'FM', nombre: 'Micronesia', dial: '+691' },
  { iso: 'MD', nombre: 'Moldavia', dial: '+373' },
  { iso: 'MC', nombre: 'Mónaco', dial: '+377' },
  { iso: 'MN', nombre: 'Mongolia', dial: '+976' },
  { iso: 'ME', nombre: 'Montenegro', dial: '+382' },
  { iso: 'MS', nombre: 'Montserrat', dial: '+1' },
  { iso: 'MZ', nombre: 'Mozambique', dial: '+258' },
  { iso: 'MM', nombre: 'Myanmar (Birmania)', dial: '+95' },
  { iso: 'NA', nombre: 'Namibia', dial: '+264' },
  { iso: 'NR', nombre: 'Nauru', dial: '+674' },
  { iso: 'NP', nombre: 'Nepal', dial: '+977' },
  { iso: 'NI', nombre: 'Nicaragua', dial: '+505' },
  { iso: 'NE', nombre: 'Níger', dial: '+227' },
  { iso: 'NG', nombre: 'Nigeria', dial: '+234' },
  { iso: 'NU', nombre: 'Niue', dial: '+683' },
  { iso: 'NO', nombre: 'Noruega', dial: '+47' },
  { iso: 'NC', nombre: 'Nueva Caledonia', dial: '+687' },
  { iso: 'NZ', nombre: 'Nueva Zelanda', dial: '+64' },
  { iso: 'OM', nombre: 'Omán', dial: '+968' },
  { iso: 'NL', nombre: 'Países Bajos', dial: '+31' },
  { iso: 'PK', nombre: 'Pakistán', dial: '+92' },
  { iso: 'PW', nombre: 'Palaos', dial: '+680' },
  { iso: 'PS', nombre: 'Palestina', dial: '+970' },
  { iso: 'PA', nombre: 'Panamá', dial: '+507' },
  { iso: 'PG', nombre: 'Papúa Nueva Guinea', dial: '+675' },
  { iso: 'PY', nombre: 'Paraguay', dial: '+595' },
  { iso: 'PE', nombre: 'Perú', dial: '+51' },
  { iso: 'PF', nombre: 'Polinesia Francesa', dial: '+689' },
  { iso: 'PL', nombre: 'Polonia', dial: '+48' },
  { iso: 'PT', nombre: 'Portugal', dial: '+351' },
  { iso: 'PR', nombre: 'Puerto Rico', dial: '+1' },
  { iso: 'GB', nombre: 'Reino Unido', dial: '+44' },
  { iso: 'CF', nombre: 'República Centroafricana', dial: '+236' },
  { iso: 'CD', nombre: 'República Democrática del Congo', dial: '+243' },
  { iso: 'DO', nombre: 'República Dominicana', dial: '+1' },
  { iso: 'RE', nombre: 'Reunión', dial: '+262' },
  { iso: 'RW', nombre: 'Ruanda', dial: '+250' },
  { iso: 'RO', nombre: 'Rumanía', dial: '+40' },
  { iso: 'RU', nombre: 'Rusia', dial: '+7' },
  { iso: 'EH', nombre: 'Sáhara Occidental', dial: '+212' },
  { iso: 'WS', nombre: 'Samoa', dial: '+685' },
  { iso: 'AS', nombre: 'Samoa Americana', dial: '+1' },
  { iso: 'BL', nombre: 'San Bartolomé', dial: '+590' },
  { iso: 'KN', nombre: 'San Cristóbal y Nieves', dial: '+1' },
  { iso: 'SM', nombre: 'San Marino', dial: '+378' },
  { iso: 'MF', nombre: 'San Martín', dial: '+590' },
  { iso: 'PM', nombre: 'San Pedro y Miquelón', dial: '+508' },
  { iso: 'VC', nombre: 'San Vicente y las Granadinas', dial: '+1' },
  { iso: 'SH', nombre: 'Santa Elena', dial: '+290' },
  { iso: 'LC', nombre: 'Santa Lucía', dial: '+1' },
  { iso: 'ST', nombre: 'Santo Tomé y Príncipe', dial: '+239' },
  { iso: 'SN', nombre: 'Senegal', dial: '+221' },
  { iso: 'RS', nombre: 'Serbia', dial: '+381' },
  { iso: 'SC', nombre: 'Seychelles', dial: '+248' },
  { iso: 'SL', nombre: 'Sierra Leona', dial: '+232' },
  { iso: 'SG', nombre: 'Singapur', dial: '+65' },
  { iso: 'SX', nombre: 'Sint Maarten', dial: '+1' },
  { iso: 'SY', nombre: 'Siria', dial: '+963' },
  { iso: 'SO', nombre: 'Somalia', dial: '+252' },
  { iso: 'LK', nombre: 'Sri Lanka', dial: '+94' },
  { iso: 'ZA', nombre: 'Sudáfrica', dial: '+27' },
  { iso: 'SD', nombre: 'Sudán', dial: '+249' },
  { iso: 'SS', nombre: 'Sudán del Sur', dial: '+211' },
  { iso: 'SE', nombre: 'Suecia', dial: '+46' },
  { iso: 'CH', nombre: 'Suiza', dial: '+41' },
  { iso: 'SR', nombre: 'Surinam', dial: '+597' },
  { iso: 'SJ', nombre: 'Svalbard y Jan Mayen', dial: '+47' },
  { iso: 'TH', nombre: 'Tailandia', dial: '+66' },
  { iso: 'TW', nombre: 'Taiwán', dial: '+886' },
  { iso: 'TZ', nombre: 'Tanzania', dial: '+255' },
  { iso: 'TJ', nombre: 'Tayikistán', dial: '+992' },
  { iso: 'IO', nombre: 'Territorio Británico del Océano Índico', dial: '+246' },
  { iso: 'TL', nombre: 'Timor Oriental', dial: '+670' },
  { iso: 'TG', nombre: 'Togo', dial: '+228' },
  { iso: 'TK', nombre: 'Tokelau', dial: '+690' },
  { iso: 'TO', nombre: 'Tonga', dial: '+676' },
  { iso: 'TT', nombre: 'Trinidad y Tobago', dial: '+1' },
  { iso: 'TN', nombre: 'Túnez', dial: '+216' },
  { iso: 'TM', nombre: 'Turkmenistán', dial: '+993' },
  { iso: 'TR', nombre: 'Turquía', dial: '+90' },
  { iso: 'TV', nombre: 'Tuvalu', dial: '+688' },
  { iso: 'UA', nombre: 'Ucrania', dial: '+380' },
  { iso: 'UG', nombre: 'Uganda', dial: '+256' },
  { iso: 'UY', nombre: 'Uruguay', dial: '+598' },
  { iso: 'UZ', nombre: 'Uzbekistán', dial: '+998' },
  { iso: 'VU', nombre: 'Vanuatu', dial: '+678' },
  { iso: 'VE', nombre: 'Venezuela', dial: '+58' },
  { iso: 'VN', nombre: 'Vietnam', dial: '+84' },
  { iso: 'WF', nombre: 'Wallis y Futuna', dial: '+681' },
  { iso: 'YE', nombre: 'Yemen', dial: '+967' },
  { iso: 'DJ', nombre: 'Yibuti', dial: '+253' },
  { iso: 'ZM', nombre: 'Zambia', dial: '+260' },
  { iso: 'ZW', nombre: 'Zimbabue', dial: '+263' }
]
